version: "3.4"

services:
  archivist:
    image: fundacionchile.azurecr.io/tranque/archivist:v1-6-1
    env_file:
      - ../base/.env.defaults
      - ../config/.env.secrets
      - ../base/.env.fixed
      - ../config/.env.archivist.secrets
    environment:
      BACKUPS_KEPT: "14"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: on-failure
    depends_on:
      - postgis
      - elasticsearch
      - storage
