# Generated by Django 2.2.11 on 2020-04-14 23:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import remotes.models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_auto_20200406_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintent',
            name='attended_by_destination_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userintent',
            name='origin',
            field=models.CharField(default=remotes.models.current_namespace, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='userintent',
            name='sent_to_destination_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userintent',
            name='serialized_user',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userintent',
            name='issue',
            field=models.CharField(blank=True, choices=[('', 'no hay problemas'), ('insufficient-permissions', 'el usuario no tiene permisos suficientes'), ('insufficient-information', 'faltan antecedentes'), ('blocked-by-rules', 'bloqueado por reglas del sistema'), ('system-engine-error', 'error del sistema durante la ejecución'), ('system-handler-error', 'error del mensaje al servidor')], default='', max_length=255),
        ),
    ]
