# Generated by Django 2.2.10 on 2020-05-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_auto_20200428_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicalertmessage',
            name='scope',
            field=models.CharField(choices=[('ef', 'ef'), ('emac', 'emac')], default='ef', max_length=5),
        ),
    ]
