# Generated by Django 2.2.11 on 2020-05-18 21:44

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_publicalertmessage_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlog',
            name='meta',
            field=base.fields.ValidatedJSONField(default=dict, schema={'properties': {'description': {'type': 'string'}, 'message': {'type': 'string'}, 'next_archived': {'type': 'boolean'}, 'next_evaluable': {'type': 'boolean'}, 'next_state': {'type': 'string'}, 'previous_archived': {'type': 'boolean'}, 'previous_evaluable': {'type': 'boolean'}, 'previous_state': {'oneOf': [{'type': 'string'}, {'type': 'null'}]}}, 'type': 'object'}),
        ),
    ]
