# Generated by Django 2.2.12 on 2020-06-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0012_alertdisconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicalertmessage',
            name='alert_type',
            field=models.CharField(choices=[('YELLOW', 'Public yellow alert message'), ('RED', 'Public red alert message'), ('GREEN', 'Public message with no alerts'), ('GRAY', 'Public disconnected alert message')], max_length=25),
        ),
    ]
