# Generated by Django 2.2.13 on 2020-06-12 21:37

import base.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200210_1929'),
        ('targets', '0039_auto_20200612_2137'),
        ('alerts', '0013_auto_20200604_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertdisconnection',
            name='scope',
            field=models.CharField(choices=[('ef', 'ef'), ('emac', 'emac')], default='ef', max_length=5),
        ),
        migrations.CreateModel(
            name='ManualAlertLog',
            fields=[
                ('id', models.CharField(default=base.fields.generate_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('scope', models.CharField(choices=[('ef', 'ef'), ('emac', 'emac')], default='ef', max_length=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='_manualalertlog_documents_+', to='documents.Document')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_alerts', to='targets.Target')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_alert_log', to='alerts.Ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
