{
 "title": "Tranque Production Vertical Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "2s",
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage by service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{id=~\"/docker/.*\",container_label_com_docker_swarm_service_name=~\"tranque-prod.*\"}) by (container_label_com_docker_swarm_service_name) ",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "CPU usage by service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{id=~\"/docker/.*\",container_label_com_docker_swarm_service_name=~\"tranque-prod.*\"}[1m])) by (container_label_com_docker_swarm_service_name) * 100 ",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  { "title": "Container last seen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Proxy",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_proxy\"})"
    }
   ]
  },
  {
   "title": "Frontend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_frontend\"})"
    }
   ]
  },
  {
   "title": "Logstash",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_logstash\"})"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_postgis\"})"
    }
   ]
  },
  {
   "title": "Cron",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_cron\"})"
    }
   ]
  },
  {
   "title": "Enrichment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_enrichment\"})"
    }
   ]
  },
  {
   "title": "Backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 21 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_django\"})"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 21 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_redis\"})"
    }
   ]
  },
  {
   "title": "Elasticsearch",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 21 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_elasticsearch\"})"
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 21 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_amqpbroker\"})"
    }
   ]
  },
  {
   "title": "Elasticsearch Active Shards",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{monitor=\"tranque-prod-monitor\"}"
    }
   ]
  }
 ]
}