import Loader from '@miners/containers/etl/defaults/Loader';
import Validator from '@miners/containers/etl/defaults/Validator';
import Voucher from '@miners/containers/etl/defaults/Voucher';

export const EXECUTORS = [
    {
        executor: 'ef_parameter:densidad', // prefijo generico, sufijo esp
        title: 'Densidad y porcentaje de finos',
        subtitle: '',
        loader: Loader,
        validator: Validator,
        voucher: Voucher,
        header: 'Ingreso de datos - Densidad y porcentaje de finos',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_parameter:muro_laguna',
        title: 'Distancia muro laguna',
        subtitle: '',
        loader: Loader,
        validator: Validator,
        voucher: Voucher,
        header: 'Ingreso de datos - Distancia muro laguna',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_parameter:cota_laguna',
        title: 'Cota espejo de agua',
        subtitle: '',
        loader: Loader,
        validator: Validator,
        voucher: Voucher,
        header: 'Ingreso de datos - Cota espejo de agua',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_parameter:volumen_relave',
        title: 'Tonelaje de relaves acumulados',
        subtitle: '',
        loader: Loader,
        validator: Validator,
        voucher: Voucher,
        header: 'Ingreso de datos - Tonelaje de relaves acumulados',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_parameter:nivel_freatico',
        title: 'Nivel freático en la cubeta',
        subtitle: '',
        loader: Loader,
        validator: Validator,
        voucher: Voucher,
        header: 'Ingreso de datos - Nivel freático en la cubeta',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_parameter:piezometria',
        title: 'Piezometría Manual',
        subtitle: '',
        loader: Loader,
        validator: Validator,
        voucher: Voucher,
        header: 'Ingreso de datos - Piezometría manual',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_parameter:cota_coronamiento_muro',
        title: 'Cota coronamiento muro',
        subtitle: '',
        loader: Loader,
        validator: Validator,
        voucher: Voucher,
        header: 'Ingreso de datos - Cota coronamiento muro',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_parameter:cota_lamas',
        title: 'Cota lamas',
        subtitle: '',
        loader: Loader,
        validator: Validator,
        voucher: Voucher,
        header: 'Ingreso de datos - Cota lamas',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_topographic',
        title: 'Perfiles topográficos',
        subtitle: '',
        loader: Loader,
        validator: Validator,
        voucher: Voucher,
        header: 'Ingreso de datos - Perfiles topográficos',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_granulometry',
        title: 'Curvas granulométricas',
        subtitle: '',
        loader: Loader,
        validator: Validator,
        voucher: Voucher,
        header: 'Ingreso de datos - Curvas granulométricas',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_parameter:pendiente_playa',
        title: 'Pendiente de playa',
        subtitle: '',
        loader: Loader,
        validator: Validator,
        voucher: Voucher,
        header: 'Ingreso de datos - Pendiente de playa',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_deformation_monoliths',
        title: 'Deformación superficial del muro',
        subtitle: '',
        loader: Loader,
        validator: Validator,
        voucher: Voucher,
        header: 'Ingreso de datos - Deformación superficial del muro',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_deformation_inclinometers',
        title: 'Deformación internal del muro y suelo de fundación',
        subtitle: '',
        loader: Loader,
        validator: Validator,
        voucher: Voucher,
        header: 'Ingreso de datos - Deformación interna del muro y suelo de fundación',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
];
