# Generated by Django 2.2.9 on 2020-02-07 20:31

import base.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reportforms.schema


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportforms', '0006_auto_20200203_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportforminstance',
            name='comment',
        ),
        migrations.AlterField(
            model_name='reportformversion',
            name='form_schema',
            field=base.fields.ValidatedJSONField(default=reportforms.schema.get_default_form, schema={'properties': {'steps': {'items': {'properties': {'sections': {'items': {'properties': {'fields': {'items': {'anyOf': [{'properties': {'key': {'minLength': 1, 'type': 'string'}, 'label': {'minLength': 1, 'type': 'string'}, 'suffix': {'type': 'string'}, 'type': {'enum': ['text'], 'type': 'string'}}, 'required': ['type', 'key', 'label'], 'type': 'object'}, {'properties': {'key': {'minLength': 1, 'type': 'string'}, 'label': {'minLength': 1, 'type': 'string'}, 'type': {'enum': ['textarea'], 'type': 'string'}}, 'required': ['type', 'key', 'label'], 'type': 'object'}, {'properties': {'key': {'minLength': 1, 'type': 'string'}, 'options': {'items': {'properties': {'key': {'minLength': 1, 'type': 'string'}, 'label': {'minLength': 1, 'type': 'string'}}, 'type': 'object'}, 'type': 'array'}, 'type': {'enum': ['checkbox'], 'type': 'string'}}, 'required': ['type', 'key', 'options'], 'type': 'object'}, {'properties': {'key': {'minLength': 1, 'type': 'string'}, 'options': {'items': {'properties': {'label': {'minLength': 1, 'type': 'string'}, 'value': {'type': ['string', 'number', 'boolean']}}, 'type': 'object'}, 'type': 'array'}, 'type': {'enum': ['select'], 'type': 'string'}}, 'required': ['type', 'key', 'label', 'options'], 'type': 'object'}, {'properties': {'inputLabel': {'type': 'string'}, 'key': {'minLength': 1, 'type': 'string'}, 'options': {'items': {'properties': {'allowText': {'type': 'boolean'}, 'label': {'minLength': 1, 'type': 'string'}, 'value': {'type': ['string', 'number', 'boolean']}}, 'type': 'object'}, 'type': 'array'}, 'type': {'enum': ['radio'], 'type': 'string'}}, 'required': ['type', 'key', 'options'], 'type': 'object'}, {'properties': {'columns': {'items': {'properties': {'header': {'minLength': 1, 'type': 'string'}, 'type': {'enum': ['label', 'text'], 'type': 'string'}, 'values': {'items': {'type': 'string'}, 'type': 'array'}}, 'type': 'object'}, 'type': 'array'}, 'key': {'minLength': 1, 'type': 'string'}, 'type': {'enum': ['table'], 'type': 'string'}}, 'required': ['type', 'key', 'columns'], 'type': 'object'}]}, 'type': 'array'}, 'title': {'type': 'string'}}, 'required': ['title', 'fields'], 'type': 'object'}, 'type': 'array'}, 'title': {'type': 'string'}}, 'required': ['title', 'sections'], 'type': 'object'}, 'type': 'array'}, 'title': {'type': 'string'}}, 'required': ['title', 'steps'], 'type': 'object'}),
        ),
        migrations.CreateModel(
            name='ReportFormComment',
            fields=[
                ('id', models.CharField(default=base.fields.generate_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('form_instance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reportforms.ReportFormInstance')),
            ],
        ),
    ]
