# Generated by Django 2.2.9 on 2020-04-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportforms', '0007_auto_20200207_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportforminstance',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('new_sending', 'Sending'), ('new_sent', 'Sent'), ('answer_to_validate', 'To Validate'), ('answer_validated', 'Answer Validated'), ('answer_sending', 'Answer Sending'), ('answer_sent', 'Answer Sent'), ('answer_received', 'Answer Received'), ('answer_reviewed', 'Answer Reviewed')], default='new_sending', max_length=200),
        ),
    ]
