# Generated by Django 2.1 on 2019-04-12 19:20

import base.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0021_timeseries_template_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.CharField(default=base.fields.generate_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=1020, upload_to='data-files/%Y.%m/')),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ETLCleanedValue',
            fields=[
                ('id', models.CharField(default=base.fields.generate_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('sheet_number', models.IntegerField()),
                ('sheet_name', models.CharField(blank=True, max_length=510, null=True)),
                ('linenumber', models.IntegerField()),
                ('group', models.CharField(blank=True, max_length=510)),
                ('source', models.CharField(blank=True, max_length=510)),
                ('series', models.CharField(blank=True, max_length=510)),
                ('value', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('x_coord', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('y_coord', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('z_coord', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('label', models.CharField(blank=True, max_length=510)),
            ],
            options={
                'ordering': ['operation', 'sheet_number', 'linenumber'],
            },
        ),
        migrations.CreateModel(
            name='ETLConformedValue',
            fields=[
                ('id', models.CharField(default=base.fields.generate_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('sheet_number', models.IntegerField()),
                ('sheet_name', models.CharField(blank=True, max_length=510, null=True)),
                ('linenumber', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=8, max_digits=16)),
                ('timestamp', models.DateTimeField()),
                ('x_coord', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('y_coord', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('z_coord', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('label', models.CharField(blank=True, max_length=510)),
            ],
            options={
                'ordering': ['operation', 'sheet_number', 'linenumber'],
            },
        ),
        migrations.CreateModel(
            name='ETLExtractedValue',
            fields=[
                ('id', models.CharField(default=base.fields.generate_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('sheet_number', models.IntegerField()),
                ('sheet_name', models.CharField(blank=True, max_length=510, null=True)),
                ('linenumber', models.IntegerField()),
                ('data', base.fields.ValidatedJSONField(default=list, schema={'items': {'type': 'object'}, 'type': 'array'})),
            ],
            options={
                'ordering': ['operation', 'sheet_number', 'linenumber'],
            },
        ),
        migrations.CreateModel(
            name='ETLOperation',
            fields=[
                ('id', models.CharField(default=base.fields.generate_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('started', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_state', models.DateTimeField(auto_now=True, db_index=True)),
                ('state', models.CharField(choices=[('extract', 'Extraction phase'), ('clean', 'Clean phase'), ('conform', 'Conform phase'), ('deliver', 'Deliver phase'), ('success', 'Successful')], db_index=True, default='extract', max_length=127)),
                ('finished', models.BooleanField(default=False)),
                ('errors', base.fields.ValidatedJSONField(blank=True, default=list, null=True, schema={'items': {'properties': {'code': {'type': 'string'}, 'linenumber': {'type': 'number'}, 'message': {'type': 'string'}, 'sheet_name': {'type': 'string'}, 'sheet_number': {'type': 'number'}}, 'required': ['code', 'message'], 'type': 'object'}, 'type': 'array'})),
                ('executor', models.CharField(max_length=127)),
                ('initial_context', base.fields.ValidatedJSONField(blank=True, default=dict, null=True, schema={'type': 'object'})),
                ('data_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_operations', to='etl.DataFile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.Target')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
        migrations.AddField(
            model_name='etlextractedvalue',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_values', to='etl.ETLOperation'),
        ),
        migrations.AddField(
            model_name='etlconformedvalue',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conformed_values', to='etl.ETLOperation'),
        ),
        migrations.AddField(
            model_name='etlconformedvalue',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='targets.Timeseries'),
        ),
        migrations.AddField(
            model_name='etlcleanedvalue',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaned_values', to='etl.ETLOperation'),
        ),
    ]
