# Generated by Django 2.1 on 2019-09-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etloperation',
            name='executor',
            field=models.CharField(db_index=True, max_length=127),
        ),
    ]
