# Generated by Django 2.1 on 2019-10-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_auto_20190911_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlcleanedvalue',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etlconformedvalue',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
