---
- name:          40-copy-files-smc
  hosts:         role_tranque-dpais-qa-smc
  vars:
    server_user: ec2-user
  remote_user:   "{{ server_user }}"
  become:        yes
  become_user:   root
  tasks:

  - name:        create root folder
    file:
      path:      "/home/{{ server_user }}/stack"
      state:     directory
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      u+rwx,g+rx-w,o+rx-w

  - name:        create rabbitmq conf directory
    file:
      path:      "/home/{{ server_user }}/stack/rabbitmq"
      state:     directory
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      u+rwx,g+rx-w,o+rx-w

  - name:        copy rabbitmq.conf
    copy:
      src:       ../assets/smc/rabbitmq/rabbitmq.conf
      dest:      "/home/{{ server_user }}/stack/rabbitmq/rabbitmq.conf"
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      u+rw-x,g+r-wx,o+r-wx

  - name:        copy rabbit definitions
    copy:
      src:       ../assets/smc/rabbitmq/definitions.json.secrets
      dest:      "/home/{{ server_user }}/stack/rabbitmq/rabbitmq.definitions.json"
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      u+rw-x,g+r-wx,o+r-wx

  - name:        create nginx conf directory
    file:
      path:      "/home/{{ server_user }}/stack/nginx"
      state:     directory
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      u+rwx,g+rx-w,o+rx-w

  - name:        copy nginx default.conf
    copy:
      src:       ../assets/smc/nginx/default.conf
      dest:      "/home/{{ server_user }}/stack/nginx/default.conf"
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      u+rw-x,g+r-wx,o+r-wx

  - name:        copy SSL certificate and key
    copy:
      src:       "../assets/{{ item }}"
      dest:      "/home/{{ server_user }}/stack/nginx/{{ item }}"
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      u+rw-x,g+r-wx,o+r-wx
    with_items:
      - fullchain.pem
      - privkey.pem

  - name:        copy stack definition files
    copy:
      src:       "../assets/smc/{{ item }}"
      dest:      "/home/{{ server_user }}/stack/{{ item }}"
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      u+rw-x,g+r-wx,o+r-wx
    with_items:
      - docker-compose.yml
      - .env
      - .secrets

  - name:        copy setup package
    copy:
      src:       ../assets/smc/setup-package
      dest:      "/home/{{ server_user }}/stack"
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      preserve
