---
- name:          42-copy-files-sml-disconnected
  hosts:         role_tranque-dpais-qa-sml-disconnected
  vars:
    server_user: ec2-user
  remote_user:   "{{ server_user }}"
  become:        yes
  become_user:   root
  tasks:

  - name:        create root folder
    file:
      path:      "/home/{{ server_user }}/stack"
      state:     directory
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      u+rwx,g+rx-w,o+rx-w

  - name:        create nginx conf directory
    file:
      path:      "/home/{{ server_user }}/stack/nginx"
      state:     directory
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      u+rwx,g+rx-w,o+rx-w

  - name:        copy nginx default.conf
    copy:
      src:       ../assets/sml-disconnected/nginx/default.conf
      dest:      "/home/{{ server_user }}/stack/nginx/default.conf"
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      u+rw-x,g+r-wx,o+r-wx

  - name:        copy stack definition files
    copy:
      src:       "../assets/sml-disconnected/{{ item }}"
      dest:      "/home/{{ server_user }}/stack/{{ item }}"
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      u+rw-x,g+r-wx,o+r-wx
    with_items:
      - docker-compose.yml
      - .env
      - .secrets

  - name:        copy setup package
    copy:
      src:       ../assets/sml-disconnected/setup-package
      dest:      "/home/{{ server_user }}/stack"
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      preserve
