apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scale-front
  namespace: tranque
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-svr
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
