# Generated by Django 2.1 on 2018-11-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0002_auto_20181106_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
