FROM python:3.6-jessie

RUN apt-get update && \
  apt-get install -y \
  netcat && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
