remotes:
  - namespace: global-namespace
    exchange: federated.global-namespace
    bucket: smc

  - namespace: ct-sml
    exchange: federated.ct-sml
    bucket: sml
    targets:
      - primero
      - segundo
      - tercero
      - cuarto
