{
 "title": "SML Inria General Infrastructure",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "2s",
 "panels": [
  { "title": "Infrastructure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (container_label_com_docker_compose_service) (container_tasks_state{state=\"running\",container_label_com_docker_compose_project=\"1-node\"}))"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (id) (container_tasks_state{state=\"running\",container_label_com_docker_compose_project=\"1-node\"})) - 1"
    }
   ]
  },
  {
   "title": "DB conns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends)"
    }
   ]
  },
  {
   "title": "Rabbit conns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(rabbitmq_connectionsTotal)" }
   ]
  },
  { "title": "Clock", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 } },
  {
   "title": "Elasticsearch documents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_docs)"
    }
   ]
  },
  {
   "title": "Redis hits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(redis_keyspace_hits_total)" }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Memory usage by service",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{id=~\"/docker/.*\",container_label_com_docker_compose_project=\"1-node\"}) by (container_label_com_docker_compose_service) ",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "CPU usage by service",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{id=~\"/docker/.*\",container_label_com_docker_compose_project=\"1-node\"}[1m])) by (container_label_com_docker_compose_service) * 100",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  { "title": "Container last seen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Proxy",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_compose_service=\"proxy\"})"
    }
   ]
  },
  {
   "title": "E700 Frontend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_compose_service=\"e700-frontend\"})"
    }
   ]
  },
  {
   "title": "Mineras Frontend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_compose_service=\"mineras-frontend\"})"
    }
   ]
  },
  {
   "title": "Backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_compose_service=\"django\"})"
    }
   ]
  },
  {
   "title": "Cron",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_compose_service=\"cron\"})"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_compose_service=\"postgis\"})"
    }
   ]
  },
  {
   "title": "Elasticsearch",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_compose_service=\"elasticsearch\"})"
    }
   ]
  },
  {
   "title": "Enrichment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_compose_service=\"enrichment\"})"
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_compose_service=\"amqpbroker\"})"
    }
   ]
  },
  {
   "title": "Logstash",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_compose_service=\"logstash\"})"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_compose_service=\"redis\"})"
    }
   ]
  },
  {
   "title": "Beats",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_compose_service=\"beats-consumer\"})"
    }
   ]
  }
 ]
}