# Generated by Django 2.1 on 2019-05-14 22:41

import base.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import remotes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(default=base.fields.generate_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('command', models.CharField(db_index=True, max_length=510)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('exchange', models.CharField(db_index=True, max_length=510)),
                ('origin', models.CharField(db_index=True, default=remotes.models.current_namespace, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('response', models.ManyToManyField(related_name='request', to='remotes.Message')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('id', models.CharField(default=base.fields.generate_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
