# Generated by Django 2.1 on 2019-05-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0002_remote_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remote',
            name='exchange',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
