# Generated by Django 2.1 on 2019-09-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0005_auto_20190704_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='remote',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
