# Generated by Django 2.1 on 2020-01-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0008_datadumprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadumprequest',
            name='groups_file',
            field=models.FileField(blank=True, max_length=1020, null=True, upload_to='dumps/'),
        ),
        migrations.AddField(
            model_name='datadumprequest',
            name='sources_file',
            field=models.FileField(blank=True, max_length=1020, null=True, upload_to='dumps/'),
        ),
    ]
