variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build builder
  - build ci helper

docker-push-builder:
  stage: build builder
  only:
    - master
  tags:
    - docker
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - docker build -t "${CI_REGISTRY_IMAGE}:latest" --build-arg "COMMIT=${CI_COMMIT_SHA}" builder
    - docker push "${CI_REGISTRY_IMAGE}:latest"

docker-push-ci-helper:
  stage: build ci helper
  only:
    - master
  tags:
    - docker
  image: docker:19.03.0
  services:
    - docker:19.03.0-dind
  script:
    - docker login -u gitlab-ci-token -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - docker build -t "${CI_REGISTRY_IMAGE}/ci-helper:latest" ci
    - docker push "${CI_REGISTRY_IMAGE}/ci-helper:latest"
