# Generated by Django 2.1 on 2019-07-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0004_remote_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remote',
            name='bucket',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
