# Generated by Django 2.1 on 2019-12-27 18:39

import base.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0030_auto_20191120_1754'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remotes', '0006_remote_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTraceRequest',
            fields=[
                ('id', models.CharField(default=base.fields.generate_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=510)),
                ('state', models.CharField(choices=[('waiting_response', 'Waiting Response'), ('received', 'Received')], default='waiting_response', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('timeseries', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='targets.Timeseries')),
            ],
        ),
    ]
