# Generated by Django 2.2.10 on 2020-02-14 17:54

import base.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0009_auto_20200115_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionHash',
            fields=[
                ('id', models.CharField(default=base.fields.generate_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('manifest_versions', base.fields.ValidatedJSONField(default=list, schema={'items': {'minLength': 1, 'type': 'string'}, 'type': 'array'})),
                ('hashes_set', base.fields.ValidatedJSONField(default=list, schema={'items': {'minLength': 1, 'type': 'array'}, 'type': 'array'})),
                ('is_valid_set', base.fields.ValidatedJSONField(default=list, schema={'items': {'minLength': 1, 'type': 'array'}, 'type': 'array'})),
                ('remote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotes.Remote')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
