# Deployment for frontend files

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: static-svr
  name: static-svr
  namespace: tranque
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-svr
  template:
    metadata:
      labels:
        app: static-svr
    spec:
      containers:
      - image: tranqueacr1.azurecr.io/tranque/django-static:v1-6-2
        name: static-svr
        resources:
          limits:
            cpu: 512m
            memory: 256Mi
          requests:
            cpu: 256m
            memory: 128Mi
