version: '3.7'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
  minio:
    image: minio/minio:RELEASE.2020-04-23T00-58-49Z
    volumes:
      - /mnt/storagetranque2:/data
    ports:
      - "80:9000"
    environment:
      MINIO_ACCESS_KEY: sysadmin
      MINIO_SECRET_KEY: "E/9z9essOPCBE1zHFtiWdvSyVu0ipLFb7nyKUS7eoXY="
    command: ["server", "/data"]
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/"]
      interval: 30s
      timeout: 20s
      retries: 3
