# Generated by Django 2.2.9 on 2020-05-15 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportforms', '0008_auto_20200428_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcase',
            name='reassign_to',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance', to='reportforms.ReportFormInstance'),
        ),
        migrations.AddField(
            model_name='reportforminstance',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
