# Generated by Django 2.1 on 2018-11-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
