# Generated by Django 2.1 on 2019-12-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_auto_20181107_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteParameter',
            fields=[
                ('name', models.CharField(max_length=510, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, default='')),
            ],
        ),
    ]
