import ETLLoader from '@miners/containers/EMAC/etl/EMACETLLoader';
import ETLValidator from '@miners/containers/EMAC/etl/EMACETLValidator';
import ETLVoucher from '@miners/containers/EMAC/etl/EMACETLVoucher';
import {API_HOST} from '@app/config';

export const EXECUTORS = [
    {
        executor: 'ef_parameter:densidad', // prefijo generico, sufijo esp
        title: 'Densidad y porcentaje de finos',
        subtitle: '',
        context: {shape: 'parameter_sector'},
        sample: `${API_HOST}/static/etl/samples/Planilla-Densidad_y_porcentaje_finos.xlsx`,
        loader: ETLLoader,
        validator: ETLValidator,
        voucher: ETLVoucher,
        header: 'Ingreso de datos - Densidad y porcentaje de finos',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_parameter:muro_laguna',
        title: 'Distancia muro laguna',
        subtitle: '',
        context: {shape: 'parameter_sector'},
        sample: `${API_HOST}/static/etl/samples/Planilla-Distancia_muro_laguna.xlsx`,
        loader: ETLLoader,
        validator: ETLValidator,
        voucher: ETLVoucher,
        header: 'Ingreso de datos - Distancia muro laguna',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_parameter:cota_laguna',
        title: 'Cota espejo de agua',
        subtitle: '',
        context: {shape: 'only_parameter'},
        sample: `${API_HOST}/static/etl/samples/Planilla-Cota_espejo_agua.xlsx`,
        loader: ETLLoader,
        validator: ETLValidator,
        voucher: ETLVoucher,
        header: 'Ingreso de datos - Cota espejo de agua',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_parameter:volumen_relave',
        title: 'Tonelaje de relaves acumulados',
        subtitle: '',
        context: {shape: 'only_parameter'},
        sample: `${API_HOST}/static/etl/samples/Planilla-Tonelaje_relaves_acumulados.xlsx`,
        loader: ETLLoader,
        validator: ETLValidator,
        voucher: ETLVoucher,
        header: 'Ingreso de datos - Tonelaje de relaves acumulados',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_parameter:nivel_freatico',
        title: 'Nivel freático en la cubeta',
        subtitle: '',
        context: {series: 'ef-mvp.m2.parameters.discrete.nivel-freatico', shape: 'sector_instrument'},
        sample: `${API_HOST}/static/etl/samples/Planilla-Nivel_freatico_en_cubeta.xlsx`,
        loader: ETLLoader,
        validator: ETLValidator,
        voucher: ETLVoucher,
        header: 'Ingreso de datos - Nivel freático en la cubeta',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_parameter:piezometria',
        title: 'Piezometría Manual',
        subtitle: '',
        context: {series: 'ef-mvp.m2.parameters.presion-poros-manual', shape: 'sector_instrument'},
        sample: `${API_HOST}/static/etl/samples/Plantilla-Piezometria_manual.xlsx`,
        loader: ETLLoader,
        validator: ETLValidator,
        voucher: ETLVoucher,
        header: 'Ingreso de datos - Piezometría manual',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_parameter:cota_coronamiento_muro',
        title: 'Cota coronamiento muro',
        subtitle: '',
        context: {series: 'ef-mvp.m2.parameters.altura-muro', shape: 'sector_instrument'},
        sample: `${API_HOST}/static/etl/samples/Planilla-Cota_coronamiento_muro.xlsx`,
        loader: ETLLoader,
        validator: ETLValidator,
        voucher: ETLVoucher,
        header: 'Ingreso de datos - Cota coronamiento muro',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_parameter:cota_lamas',
        title: 'Cota lamas',
        subtitle: '',
        context: {series: 'ef-mvp.m2.parameters.variables.cota-lamas', shape: 'sector_instrument'},
        sample: `${API_HOST}/static/etl/samples/Plantilla-Cota_lamas.xlsx`,
        loader: ETLLoader,
        validator: ETLValidator,
        voucher: ETLVoucher,
        header: 'Ingreso de datos - Cota lamas',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_topographic',
        title: 'Perfiles topográficos',
        subtitle: '',
        context: '',
        sample: `${API_HOST}/static/etl/samples/Plantilla-Perfiles _topograficos.xlsx`,
        loader: ETLLoader,
        validator: ETLValidator,
        voucher: ETLVoucher,
        header: 'Ingreso de datos - Perfiles topográficos',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    },
    {
        executor: 'ef_granulometry',
        title: 'Curvas granulométricas',
        subtitle: '',
        context: '',
        sample: `${API_HOST}/static/etl/samples/Plantilla-Granulometria.xlsx`,
        loader: ETLLoader,
        validator: ETLValidator,
        voucher: ETLVoucher,
        header: 'Ingreso de datos - Curvas granulométricas',
        subheader: '',
        description: '',
        loaderRoute: 'miners.target.ef.dataLoad.fromFile',
        exitRoute: 'miners.target.ef.registry.operationList'
    }
];
