# Regular application variables are stored here

apiVersion: v1
kind: ConfigMap
metadata:
  name: configs
  namespace: tranque
data:
  api-base: https://w2.onr.cl/api
  static-url: https://static.onr.cl/static/
  s3-access-key-id: sysadmin
  s3-bucket-name: smc
  s3-endpoint-url: http://172.30.3.4/
  redis-host: REDIS-SNGM.redis.cache.windows.net
  redis-port: "6380"
  redis-ssl: "1"

# Modificar o agregar valores

  # Este dato se obtiene desde el private-link
  postgres-host: 172.30.4.4 # db-sngm.postgres.database.azure.com
  postgres-user: sysadmin@db-sngm

  # Estos datos se obtienen una vez creado los servicios
  elasticsearch-protocol: http
  elasticsearch-host: 172.30.4.8
  elasticsearch-port: "9200"
  elasticsearch-user: sysadmin

  amqp-host: sassy-tiger.rmq.cloudamqp.com
  amqp-ssl: "1"
  amqp-username: ffzeosss
  amqp-port: "5671"
  amqp-vhost: /ffzeosss
  amqp-federated-queue: central-queue
