# Service

apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-svc
  name: front-svc
  namespace: tranque
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 443-443
    port: 443
    protocol: TCP
    targetPort: 80
  selector:
    app: front-svr
  clusterIP: 10.0.126.190
  type: LoadBalancer
