# Generated by Django 2.1 on 2018-10-26 20:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0004_auto_20181026_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquiredprotocol',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
    ]
