# Generated by Django 2.1 on 2018-11-18 01:43

import base.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0009_timeseries_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formset',
            fields=[
                ('id', models.CharField(default=base.fields.generate_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('informative_timeseries', models.ManyToManyField(blank=True, related_name='informed_formsets', to='targets.Timeseries')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='targets.Target')),
                ('timeseries', models.ManyToManyField(blank=True, related_name='formsets', to='targets.Timeseries')),
            ],
            options={
                'ordering': ['target', 'title'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='formset',
            unique_together={('target', 'title')},
        ),
    ]
