# Generated by Django 2.1 on 2019-01-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0012_auto_20181126_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='script_version',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
    ]
