# Generated by Django 2.1 on 2019-02-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0014_auto_20190110_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequency',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'frequencies'},
        ),
    ]
