# Generated by Django 2.1 on 2019-03-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0015_auto_20190218_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='space_coords',
            field=models.CharField(blank=True, choices=[('x', 'X'), ('y', 'Y'), ('z', 'Z'), ('xy', 'X, Y'), ('xz', 'X, Z'), ('yz', 'Y, Z'), ('xyz', 'X, Y, Z')], max_length=3, null=True),
        ),
    ]
