# Generated by Django 2.1 on 2019-04-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0019_auto_20190325_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='type',
            field=models.CharField(choices=[('manual', 'Manually input series'), ('raw', 'Raw series'), ('derived', 'Derived series'), ('test', 'Test series')], db_index=True, default='raw', max_length=127),
        ),
    ]
