# Generated by Django 2.1 on 2019-05-28 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0003_auto_20190523_1618'),
        ('targets', '0023_auto_20190528_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='remote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='remotes.Remote'),
        ),
    ]
