# Generated by Django 2.1 on 2019-06-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0024_target_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='threshold',
            name='kind',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
