# Generated by Django 2.1 on 2019-06-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0025_threshold_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeseries',
            old_name='range_lower',
            new_name='range_gte',
        ),
        migrations.RenameField(
            model_name='timeseries',
            old_name='range_upper',
            new_name='range_lte',
        ),
        migrations.AddField(
            model_name='timeseries',
            name='range_gt',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='timeseries',
            name='range_lt',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
    ]
