# Generated by Django 2.1 on 2020-01-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0030_auto_20191120_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ['hardware_id'], 'verbose_name': 'source'},
        ),
        migrations.AlterModelOptions(
            name='datasourcegroup',
            options={'ordering': ['target', 'canonical_name'], 'verbose_name': 'group'},
        ),
    ]
