# Generated by Django 2.2.9 on 2020-02-10 19:29

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0032_datasourcegroup_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='meta',
            field=base.fields.ValidatedJSONField(blank=True, null=True, schema={'patternProperties': {'^.*$': {'additionalProperties': False, 'properties': {'name': {'type': 'string'}, 'order': {'type': 'number'}, 'value': {'type': ['number', 'string', 'boolean', 'null']}}, 'required': ['value'], 'type': 'object'}}, 'type': 'object'}),
        ),
        migrations.AlterField(
            model_name='datasourcegroup',
            name='meta',
            field=base.fields.ValidatedJSONField(blank=True, null=True, schema={'patternProperties': {'^.*$': {'additionalProperties': False, 'properties': {'name': {'type': 'string'}, 'order': {'type': 'number'}, 'value': {'type': ['number', 'string', 'boolean', 'null']}}, 'required': ['value'], 'type': 'object'}}, 'type': 'object'}),
        ),
        migrations.AlterField(
            model_name='target',
            name='meta',
            field=base.fields.ValidatedJSONField(default=dict, schema={'patternProperties': {'^.*$': {'additionalProperties': False, 'properties': {'name': {'type': 'string'}, 'order': {'type': 'number'}, 'value': {'type': ['number', 'string', 'boolean', 'null']}}, 'required': ['value'], 'type': 'object'}}, 'type': 'object'}),
        ),
    ]
