# Generated by Django 2.2.12 on 2020-06-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200210_1929'),
        ('targets', '0037_auto_20200603_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='_timeseries_documents_+', to='documents.Document'),
        ),
    ]
