# Generated by Django 2.2.10 on 2020-06-14 07:31

import base.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0040_camera_videoframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetMap',
            fields=[
                ('id', models.CharField(default=base.fields.generate_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('canonical_name', models.CharField(choices=[('instruments-map', 'Mapa de instrumentos'), ('sectors-map', 'Esquema de sectores'), ('overflow-potential-map', 'Esquema de cuenca aportante (potencial de rebalse)')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='maps/')),
                ('lower_left_coords', base.fields.ValidatedJSONField(schema={'additionalProperties': False, 'properties': {'srid': {'type': 'number'}, 'x': {'type': 'number'}, 'y': {'type': 'number'}}, 'required': ['x', 'y'], 'type': 'object'})),
                ('upper_right_coords', base.fields.ValidatedJSONField(schema={'additionalProperties': False, 'properties': {'srid': {'type': 'number'}, 'x': {'type': 'number'}, 'y': {'type': 'number'}}, 'required': ['x', 'y'], 'type': 'object'})),
                ('target_canonical_name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
