# Generated by Django 2.2.10 on 2020-06-15 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0041_targetmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetmap',
            name='target_canonical_name',
        ),
        migrations.AddField(
            model_name='targetmap',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='maps', to='targets.Target'),
        ),
    ]
