# Generated by Django 2.2.10 on 2020-06-19 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200210_1929'),
        ('targets', '0042_auto_20200615_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datasource_sheets', to='documents.Document'),
        ),
    ]
