# Generated by Django 2.1 on 2019-03-25 13:59

import base.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSite',
            fields=[
                ('id', models.CharField(default=base.fields.generate_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=510)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Entity')),
            ],
            options={
                'ordering': ['entity', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='worksite',
            unique_together={('entity', 'name')},
        ),
    ]
