# Generated by Django 2.2.11 on 2020-03-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_auto_20200210_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('approval_level', models.PositiveIntegerField(default=1)),
                ('actions', models.ManyToManyField(blank=True, related_name='user_role', to='entities.UserAction')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='entities.UserRole'),
        ),
    ]
