# Generated by Django 2.1 on 2019-07-02 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='type',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='user',
        ),
        migrations.DeleteModel(
            name='AgentType',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
