# Generated by Django 2.2.10 on 2020-04-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_auto_20200320_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='approval_level',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='entities.UserAction'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approval_level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
