# Deployment for frontend files

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis-svr
  name: redis-svr
  namespace: tranque
spec:
  replicas: 1
  serviceName: redis-srv
  selector:
    matchLabels:
      app: redis-svr
  template:
    metadata:
      labels:
        app: redis-svr
    spec:
      containers:
      - image: redis:6-alpine
        name: redis-svr
        # resources:
        #  limits:
        #    cpu: 512m
        #    memory: 256Mi
        #  requests:
        #    cpu: 256m
        #    memory: 128Mi
