# Sensitive application variables are stored here

apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: tranque
stringData:

  django-secret-key: MNR5oxQ/GkuBT7YoYaDx9DlRR4YdIcAU0pDSvDXJIR4=
  postgres-password: 7kr5SdEdw5IgESh2si_bo1gv3qbS-Cmm
  s3-secret-access-key: E/9z9essOPCBE1zHFtiWdvSyVu0ipLFb7nyKUS7eoXY=

  
#Modificar valores
 
  #Estos valores se obtienen una vez creados los servicios
  elasticsearch-password: ~Wj248a2b=Tz
  amqp-password: 7kr5SdEdw5IgESh2si_bo1gv3qbS-Cmm
  redis-password: o+1Rc0N4V4zgxJxKNerfDdVnrTuGrnfGtIQ7yaW7skA=
