---
- name:          41-copy-files-sml
  hosts:         role_tranque-qa-sml-*
  vars:
    server_user: ec2-user
  remote_user:   "{{ server_user }}"
  become:        yes
  become_user:   root
  tasks:

  # root folder
  - name:        create root folder
    file:
      path:      "/home/{{ server_user }}/stack"
      state:     directory
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      u+rwx,g+rx-w,o+rx-w

  # nginx files
  - name:        create nginx conf directory
    file:
      path:      "/home/{{ server_user }}/stack/nginx"
      state:     directory
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      u+rwx,g+rx-w,o+rx-w

  - name:        copy nginx default.conf
    copy:
      src:       ../assets/sml/nginx/default.conf
      dest:      "/home/{{ server_user }}/stack/nginx/default.conf"
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      u+rw-x,g+r-wx,o+r-wx

  - name:        copy SSL certificate and key
    copy:
      src:       "../assets/{{ item }}"
      dest:      "/home/{{ server_user }}/stack/nginx/{{ item }}"
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      u+rw-x,g+r-wx,o+r-wx
    with_items:
      - fullchain.pem
      - privkey.pem

  # copy stack files
  - name:        copy stack definition files
    copy:
      src:       "../assets/sml/{{ item }}"
      dest:      "/home/{{ server_user }}/stack/{{ item }}"
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      u+rw-x,g+r-wx,o+r-wx
    with_items:
      - docker-compose.yml
      - .env
      - .secrets
      - backup.sh

  - name:        copy faking behaviour files
    copy:
      src:       "../assets/sml/behaviours"
      dest:      "/home/{{ server_user }}/stack/behaviours"
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      preserve

  # setup package
  - name:        copy setup package
    copy:
      src:       ../assets/sml/setup-package
      dest:      "/home/{{ server_user }}/stack"
      owner:     "{{ server_user }}"
      group:     "{{ server_user }}"
      mode:      preserve
