version: "3.4"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.1
    ports:
      - 9200:9200
    environment:
      - "cluster.name=smc-test-cluster"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "discovery.zen.minimum_master_nodes=1"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "ES_JAVA_OPTS=-Xmx2g -Xms2g"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
volumes:
  elasticsearch:
