apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scale-api
  namespace: tranque
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-svr
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
