apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scale-consu
  namespace: tranque
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consu-svr
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
