---
- name:               61-clean-up-docker
  hosts:              role_docker-leader:role_docker-manager:role_docker-worker-*
  vars:
    server_user:      ec2-user
  remote_user:        "{{ server_user }}"
  become:             yes
  become_user:        root
  tasks:
  - name:             docker system prune
    docker_prune:
      containers:     yes
      images:         yes
      images_filters:
        dangling:     false
      networks:       yes
      volumes:        yes
      builder_cache:  yes
