---
- name:          16-docker-labels-postgres
  hosts:         role_docker-worker-postgres
  vars:
    server_user: ec2-user
  remote_user:   "{{ server_user }}"
  become:        yes
  become_user:   root
  tasks:
  - name:        update docker options
    lineinfile:
      path:      /etc/sysconfig/docker
      regexp:    '^OPTIONS='
      line:      'OPTIONS="--default-ulimit nofile=1024:4096 --label=tranque.server.type=worker-postgres"'
    register:    update_docker_options_output
  - name:        enable and start docker
    when:        update_docker_options_output.changed
    service:
      name:      docker
      state:     restarted
