{
 "title": "Tranque Production Horizontal Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "2s",
 "panels": [
  { "title": "Infrastructure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (container_label_com_docker_swarm_node_id) (container_tasks_state{state=\"running\",container_label_com_docker_swarm_task_name=~\"tranque-prod.*\"}))"
    }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (container_label_com_docker_swarm_service_name) (container_tasks_state{state=\"running\",container_label_com_docker_swarm_task_name=~\"tranque-prod.*\"}))"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (id) (container_tasks_state{state=\"running\",container_label_com_docker_swarm_task_name=~\"tranque-prod.*\"})) - 1"
    }
   ]
  },
  {
   "title": "DB conns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends{monitor=\"tranque-prod-monitor\"})"
    }
   ]
  },
  {
   "title": "Rabbit conns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rabbitmq_connectionsTotal{monitor=\"tranque-prod-monitor\"})"
    }
   ]
  },
  { "title": "Clock", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 } },
  {
   "title": "Elasticsearch documents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_docs{monitor=\"tranque-prod-monitor\"})"
    }
   ]
  },
  {
   "title": "Logstash events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(logstash_node_pipeline_events_in_total{monitor=\"tranque-prod-monitor\"})"
    }
   ]
  },
  {
   "title": "Redis hits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(redis_keyspace_hits_total{monitor=\"tranque-prod-monitor\"})"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Memory usage by service",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{id=~\"/docker/.*\",container_label_com_docker_swarm_service_name=~\"tranque-prod.*\"}) by (container_label_com_docker_swarm_service_name) ",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "CPU usage by service",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{id=~\"/docker/.*\",container_label_com_docker_swarm_service_name=~\"tranque-prod.*\"}[1m])) by (container_label_com_docker_swarm_service_name) * 100 ",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  { "title": "Container last seen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Proxy",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_proxy\"})"
    }
   ]
  },
  {
   "title": "Frontend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_frontend\"})"
    }
   ]
  },
  {
   "title": "Backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_django\"})"
    }
   ]
  },
  {
   "title": "Cron",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_cron\"})"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_postgis\"})"
    }
   ]
  },
  {
   "title": "Elasticsearch",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_elasticsearch\"})"
    }
   ]
  },
  {
   "title": "Enrichment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_enrichment\"})"
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_amqpbroker\"})"
    }
   ]
  },
  {
   "title": "Logstash",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_logstash\"})"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-max(container_last_seen{container_label_com_docker_swarm_service_name=\"tranque-prod_redis\"})"
    }
   ]
  },
  {
   "title": "Elasticsearch Active Shards",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{monitor=\"tranque-prod-monitor\"}"
    }
   ]
  }
 ]
}