# Generated by Django 2.1 on 2018-10-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='data_sources', to='documents.Document'),
        ),
    ]
