# Generated by Django 2.1 on 2018-10-26 18:27

import base.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_auto_20181026_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceGroup',
            fields=[
                ('id', models.CharField(default=base.fields.generate_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=510)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_source_groups', to='targets.Target')),
            ],
            options={
                'ordering': ['target', 'id'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_sources', to='targets.DataSourceGroup'),
        ),
    ]
