# Generated by Django 2.1 on 2018-11-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0007_auto_20181113_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='canonical_name',
            field=models.SlugField(editable=False, max_length=510),
        ),
    ]
