# Generated by Django 2.1 on 2018-11-20 21:58

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0010_auto_20181118_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='coords',
            field=base.fields.ValidatedJSONField(blank=True, null=True, schema={'additionalProperties': False, 'properties': {'srid': {'type': 'number'}, 'x': {'type': 'number'}, 'y': {'type': 'number'}}, 'required': ['x', 'y'], 'type': 'object'}),
        ),
        migrations.AlterField(
            model_name='target',
            name='coords',
            field=base.fields.ValidatedJSONField(blank=True, null=True, schema={'additionalProperties': False, 'properties': {'srid': {'type': 'number'}, 'x': {'type': 'number'}, 'y': {'type': 'number'}}, 'required': ['x', 'y'], 'type': 'object'}),
        ),
        migrations.AlterField(
            model_name='zone',
            name='coords',
            field=base.fields.ValidatedJSONField(schema={'additionalProperties': False, 'properties': {'srid': {'type': 'number'}, 'x': {'type': 'number'}, 'y': {'type': 'number'}}, 'required': ['x', 'y'], 'type': 'object'}),
        ),
    ]
