# Generated by Django 2.1 on 2019-01-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0013_timeseries_script_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='script_version',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
