# Generated by Django 2.1 on 2019-03-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0016_timeseries_space_coords'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formset',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='formset',
            name='informative_timeseries',
        ),
        migrations.RemoveField(
            model_name='formset',
            name='target',
        ),
        migrations.RemoveField(
            model_name='formset',
            name='timeseries',
        ),
        migrations.DeleteModel(
            name='Formset',
        ),
    ]
