# Generated by Django 2.1 on 2019-03-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20190325_1359'),
        ('targets', '0018_timeseries_data_source_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='entity',
        ),
        migrations.AddField(
            model_name='target',
            name='work_sites',
            field=models.ManyToManyField(blank=True, related_name='targets', to='entities.WorkSite'),
        ),
    ]
