# Generated by Django 2.1 on 2019-04-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0020_auto_20190404_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='template_name',
            field=models.CharField(blank=True, db_index=True, max_length=510, null=True),
        ),
    ]
