# Generated by Django 2.1 on 2019-06-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0026_auto_20190605_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='type',
            field=models.CharField(blank=True, choices=[(None, 'Undefined type'), ('online', 'On-line instrument'), ('offline', 'Off-line instrument'), ('reference', 'Reference point(s) or inert object(s)')], db_index=True, default=None, max_length=127, null=True),
        ),
    ]
