# Generated by Django 2.1 on 2019-10-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0028_timeseries_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['natural_name']},
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='natural_key',
            new_name='natural_name',
        ),
    ]
