# Generated by Django 2.2.9 on 2020-02-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0031_auto_20200116_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcegroup',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='targets.DataSourceGroup'),
        ),
    ]
