# Generated by Django 2.1 on 2020-01-22 19:24

import base.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20200116_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='alerts.Ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='close_conditions',
            field=base.fields.ValidatedJSONField(default=list, schema={'items': {'properties': {'complete': {'type': 'boolean'}, 'description': {'type': 'string'}, 'short_description': {'type': 'string'}}, 'required': ['short_description', 'description', 'complete'], 'type': 'object'}, 'type': 'array'}),
        ),
        migrations.AddField(
            model_name='ticket',
            name='evaluable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='meta',
            field=base.fields.ValidatedJSONField(default=dict, schema={'properties': {'description': {'type': 'string'}, 'events': {'items': {'type': 'object'}, 'type': 'array'}, 'next_archived': {'type': 'boolean'}, 'next_evaluable': {'type': 'boolean'}, 'next_state': {'type': 'string'}, 'previous_archived': {'type': 'boolean'}, 'previous_evaluable': {'type': 'boolean'}, 'previous_state': {'oneOf': [{'type': 'string'}, {'type': 'null'}]}}, 'type': 'object'}),
        ),
    ]
