# Generated by Django 2.1 on 2020-01-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20200123_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='groups',
            field=models.CharField(db_index=True, default='//', max_length=510),
            preserve_default=False,
        ),
    ]
