# Generated by Django 2.2.11 on 2020-04-28 23:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_auto_20200414_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorizationrequest',
            old_name='action',
            new_name='authorization',
        ),
        migrations.AddField(
            model_name='authorizationrequest',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authorizationrequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authorizationrequest',
            name='created_by',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='authorizationrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authorizationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'en espera'), ('approved', 'aprobada'), ('approved_and_used', 'usada'), ('denied', 'denegada')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userintent',
            name='issue',
            field=models.CharField(blank=True, choices=[('', 'no hay problemas'), ('insufficient-permissions', 'el usuario no tiene permisos suficientes'), ('authorization-required', 'se requiere authorizacion para realizar esta acción'), ('insufficient-information', 'faltan antecedentes'), ('blocked-by-rules', 'bloqueado por reglas del sistema'), ('system-engine-error', 'error del sistema durante la ejecución'), ('system-handler-error', 'error del mensaje al servidor')], default='', max_length=255),
        ),
    ]
