global:
  external_labels:
      monitor: 'tranque-monitor'

rule_files:
  - "/etc/prometheus/alerting_rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tranque-dev-monitor'
    scrape_interval: 5s
    scrape_timeout: 5s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="docker"}'
        - '{job="postgis"}'
        - '{job="elasticsearch"}'
        - '{job="amqpbroker"}'
        - '{job="logstash"}'
        - '{job="redis"}'
        - '{job="ts-stats"}'
        - '{job="frontends"}'
        - '{job="backend"}'
    static_configs:
      - targets:
        - 'leader.dev.observatorioderelaves.cl:9090'

  - job_name: 'tranque-prod-monitor'
    scrape_interval: 5s
    scrape_timeout: 5s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="docker"}'
        - '{job="postgis"}'
        - '{job="elasticsearch"}'
        - '{job="amqpbroker"}'
        - '{job="logstash"}'
        - '{job="redis"}'
        - '{job="ts-stats"}'
        - '{job="frontends"}'
        - '{job="backend"}'
    static_configs:
      - targets:
        - 'leader.observatorioderelaves.cl:9090'
