# Generated by Django 2.1 on 2018-10-23 15:38

import base.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=base.fields.generate_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=1020, upload_to='documents/%Y.%m/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sha1', models.CharField(max_length=40)),
                ('meta', base.fields.ValidatedJSONField(blank=True, null=True, schema={'additionalProperties': False, 'patternProperties': {'^.*$': {'additionalProperties': False, 'properties': {'name': {'type': 'string'}, 'order': {'type': 'number'}, 'value': {'type': ['number', 'string', 'boolean', 'null']}}, 'required': ['value'], 'type': 'object'}}, 'type': 'object'})),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.DocumentType'),
        ),
    ]
